name: HTML-Header-template-pack
version: '1.1'
discription: Some HTML header templates
parts:
  hhtp:
    source: https://github.com/Tutu1021/HTML-HEADER-TEMPLATE-PACK/archive/refs/heads/master.zip
    plugin: apt
