name: html-header-template-pack
base: core18
version: '1.1'
summary: HTML beautyful header templates by Tutu1021
description: Some HTML Header Templates
grade: stable
confinement: strict
apps:
  html-header-template-pack:
    command: 
parts:
  html-header-template-pack:
    source: https://github.com/Tutu1021/HTML-HEADER-TEMPLATE-PACK/archive/refs/heads/master.zip
    plugin: apt
